export const operators = [

    { type: 'OPERATOR_EQUAL', regex: /^==/ },
    { type: 'ASSIGNMENT', regex: /^=/ },
    { type: 'PLUS', regex: /^\+/ },
    { type: 'MINUS', regex: /^-/ },
    { type: 'MULTIPLY', regex: /^\*/ },
    { type: 'DIVIDE', regex: /^\// },
    { type: 'MODULUS', regex: /^%/ },
    { type: 'INCREMENT', regex: /^\+\+/ },
    { type: 'DECREMENT', regex: /^--/ },
    { type: 'NOT_EQUAL', regex: /^!=/ },
    { type: 'GREATER_THAN', regex: /^>/ },
    { type: 'LESS_THAN', regex: /^</ },
    { type: 'GREATER_THAN_OR_EQUAL', regex: /^>=/ },
    { type: 'LESS_THAN_OR_EQUAL', regex: /^<=/ },
    { type: 'AND', regex: /^&&/ },
    { type: 'OR', regex: /^\|\|/ },
    { type: 'NOT', regex: /^!/ },
    { type: 'BITWISE_AND', regex: /^&/ },
    { type: 'BITWISE_OR', regex: /^\|/ },
    { type: 'BITWISE_XOR', regex: /^\^/ },
    { type: 'BITWISE_NOT', regex: /^~/ },
    { type: 'LEFT_SHIFT', regex: /^<</ },
    { type: 'RIGHT_SHIFT', regex: /^>>/ },
    { type: 'LEFT_SHIFT_ASSIGNMENT', regex: /^<<=/ },
    { type: 'RIGHT_SHIFT_ASSIGNMENT', regex: /^>>=/ },

];
